### ISSUE TITLE
Crash when reading metrics endpoint

### ISSUE THREAD

**Issue by jakepearson** [roylines/node-epimetheus#25]
Good morning, I tried running the `hapi` example and got the following error on startup:

```
hapi server listening on port 8002
Debug: internal, implementation, error
    TypeError: Uncaught error: undefined is not a function
    at Array.map (native)
    at Object.Registry.metrics (/Users/peajo07/projects/demos/prom/node/node_modules/prom-client/lib/registry.js:52:5)
    at Object.summary (/Users/peajo07/projects/demos/prom/node/node_modules/prom-client/lib/register.js:15:13)
    at handler (/Users/peajo07/projects/demos/prom/node/node_modules/epimetheus/lib/hapi.js:10:42)
    at Object.internals.handler (/Users/peajo07/projects/demos/prom/node/node_modules/hapi/lib/handler.js:99:36)
    at request._protect.run (/Users/peajo07/projects/demos/prom/node/node_modules/hapi/lib/handler.js:30:23)
    at module.exports.internals.Protect.internals.Protect.run (/Users/peajo07/projects/demos/prom/node/node_modules/hapi/lib/protect.js:59:12)
    at exports.execute (/Users/peajo07/projects/demos/prom/node/node_modules/hapi/lib/handler.js:24:22)
    at each (/Users/peajo07/projects/demos/prom/node/node_modules/hapi/lib/request.js:382:16)
    at iterate (/Users/peajo07/projects/demos/prom/node/node_modules/items/lib/index.js:36:13)
```

Any idea what I'm doing wrong?

thanks,
Jake

**Comment by diasdavid** [comment]
@jakepearson this PR should fix what you were seeing: https://github.com/roylines/node-epimetheus/pull/32

It has already been merged and released, check it out :)
